import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import StyledComponentsRegistry from '@/app/lib/registry';
import { AppProvider } from '@/components/providers/app-provider';

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin", "latin-ext"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} h-full antialiased`}
      data-scroll-behavior="smooth"
    >
      <body>
        <StyledComponentsRegistry>
          <AppProvider>
            {children}
          </AppProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
